*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,56 +1,71 @@
-echo "Determining Qt version... "
-qtVersionMajorRequired="3"
-qtVersionMinorRequired="3"
-qtMessage="This version of Qtstalker requires Qt$qtVersionMajorRequired.$qtVersionMinorRequired or better, but not Qt4"
-qmakeCmd=`command -v qmake`
+#!/bin/sh
+
+echo -n "Determining Qt version ..."
+qtVersionMajorRequired="4"
+qtVersionMinorRequired="5"
+qtMessage="This version of Qtstalker requires Qt$qtVersionMajorRequired.$qtVersionMinorRequired or better"
+qmakeCmd=`command -v qmake-qt4`
 qtVersionOk="false"
 if [ -z "$qmakeCmd" ] ; then
   qmakeOk="false"
+  echo " not found"
   echo "ERROR: Qt is not properly installed - cannot find 'qmake'"
 else
   qmakeOk="true"
   qtVersionOk="true"
   qtVersion=`"$qmakeCmd" --version 2>&1 | sed -n '/[0-9]\.[0-9]\.[0-9]/s/^.*\([0-9]\.[0-9]\.[0-9]\).*$/\1/p'`
-  echo "Using Qt $qtVersion"
+  echo -n " $qtVersion ..."
   qtVersionMajor=`echo $qtVersion | sed 's/^\([0-9]\)\..*$/\1/'`
   qtVersionMinor=`echo $qtVersion | sed 's/^[0-9]\.\([0-9]\)\..*$/\1/'`
   if [ $qtVersionMajor -ne $qtVersionMajorRequired ]; then
     qtVersionOk="false"
-    echo "ERROR: $qtMessage"
   elif [ $qtVersionMinor -lt $qtVersionMinorRequired ]; then
     qtVersionOk="false"
+  fi
+  if [ "$qtVersionOk" != "true" ]; then
+    echo " not okay"
     echo "ERROR: $qtMessage"
+  else
+    echo " okay"
   fi
 fi
 
-echo "Determining TA-Lib version ... "
+echo -n "Determining TA-Lib version ..."
 talibCmd=`command -v ta-lib-config`
 if [ -z "$talibCmd" ] ; then
   talibOk="false"
+  echo " not found"
   echo "ERROR: TA-Lib is not properly installed - cannot find 'ta-lib-config'"
 else
   talibOk="true"
   talibVersion=`"$talibCmd" --version`
-  echo "Using TA-Lib $talibVersion"
+  echo -n " $talibVersion ..."
+  echo " okay"
 fi
 if [ "$qmakeOk" != "true" ] || [ "$qtVersionOk" != "true" ] || [ "$talibOk" != "true" ]; then
   echo "ERROR: There were configuration issues. See docs/install.html"
   exit 1
 fi
 
-echo "Building Makefile..."
-qmake "DEFINES += QT_NO_COMPAT" "CONFIG += qt" -o Makefile qtstalker.pro
+echo
+echo "Building Makefile ..."
+qmake-qt4 "DEFINES += QT_NO_COMPAT" "CONFIG += qt" -o Makefile qtstalker.pro
+if [ "$?" -ne "0" ]; then
+  echo "ERROR: See configuration messages above."
+  exit 1
+else
+  echo "Done"
+fi
+
+echo
+echo "Creating national language files in i18n ..."
+qmake-qt4 -project -r -o qtstalker_single.pro .
+lupdate-qt4 qtstalker_single.pro
 echo "Done"
-echo "Creating national language files in i18n..."
-qmake -project -r -o qtstalker_single.pro .
-lupdate qtstalker_single.pro
+echo "Compiling existing translations ..."
+lrelease-qt4 i18n/qtstalker_??.ts
 echo "Done"
-echo "Compiling existing translations..."
-lrelease i18n/qtstalker_??.ts
-echo "Done"
-echo "You may now 'make && make install'"
 
-
-
-
+echo
+echo "You may now 'make && sudo make install'"
 
